### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Enjoyoer** [Valkam-Git/WFM-Riven-Search#3]
Upon running deal_finder.py, "ModuleNotFoundError: No module named 'requests'" pops up.

**Comment by Luis-Munu** [comment]
As you probably already know, you can solve the issue by using the command "pip install " with the library you're being asked for.

Still, the project is outdated and won't work unless the weapon data is updated so don't bother with it as of now.
